[package]
name = "error-iter"
description = "Error::iter_chain and Error::iter_sources on stable Rust"
repository = "https://github.com/parasyte/error-iter"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
readme = "README.md"
keywords = ["chain", "error", "iter", "iterator", "sources"]
categories = ["development-tools::debugging"]
license = "MIT"

[badges]
travis-ci = { repository = "parasyte/error-iter" }
maintenance = { status = "experimental" }

[dev-dependencies]
thiserror = "1.0"
